using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client._Impstation.VendingMachines;

[GenerateTypedNameReferences]
public sealed partial class VendingStoreGui : Control
{
}
