using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.EditPronouns;

/// <summary>
///     Admin Eui window to view or edit an entity's pronouns.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EditPronounsWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entityManager = default!;

    private NetEntity _target = NetEntity.Invalid;
    private Dictionary<ProtoId<PronounGrammarPrototype>, string> _pronouns = [];

    public EditPronounsWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetTargetEntity(NetEntity target)
    {
        _target = target;
        var uid = _entityManager.GetEntity(target);

        var targetName = _entityManager.EntityExists(uid)
                ? _entityManager.GetComponent<MetaDataComponent>(uid).EntityName
                : string.Empty;

        Title = targetName;
        EntityLabel.Text = targetName;
    }

    public void SetPronouns(Dictionary<ProtoId<PronounGrammarPrototype>, string> pronouns)
    {
        _pronouns = pronouns;
        PronounColumns.DisposeAllChildren();

        foreach (var pronoun in pronouns)
        {
            PronounColumns.AddChild(new Label
            {
                Text = pronoun.Key.Id
            });
            PronounColumns.AddChild(new Label
            {
                Text = pronoun.Value
            });
        }
    }
}
