using System.Linq;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects.Components.Localization;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.EditPronouns;

/// <summary>
///     Admin Eui window to view or edit an entity's pronouns.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EditPronounsWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    private readonly GrammarSystem _grammar = default!;

    private NetEntity _target = NetEntity.Invalid;
    private Dictionary<ProtoId<PronounGrammarPrototype>, string> _pronouns = [];

    public EditPronounsWindow()
    {
        IoCManager.InjectDependencies(this);
        _grammar = _entityManager.System<GrammarSystem>();
        RobustXamlLoader.Load(this);

        SaveButton.OnPressed += SavePressed;
        ResetButton.OnPressed += ResetPressed;
    }

    public void SetTargetEntity(NetEntity target)
    {
        _target = target;
        var uid = _entityManager.GetEntity(target);

        var targetName = _entityManager.EntityExists(uid)
                ? _entityManager.GetComponent<MetaDataComponent>(uid).EntityName
                : string.Empty;

        Title = Loc.GetString("edit-pronouns-title", ("targetName", targetName));
    }

    /// <summary>
    ///     Sets the list of pronouns.
    /// </summary>
    public void SetPronouns(Dictionary<ProtoId<PronounGrammarPrototype>, string> pronouns)
    {
        PronounBox.DisposeAllChildren();
        _pronouns = pronouns;

        foreach (var pronoun in pronouns)
        {
            var columns = new GridContainer { Columns = 2, MinSize = new Vector2(70, 70) };
            PronounBox.AddChild(columns);

            columns.AddChild(new Label
            {
                Text = pronoun.Key.Id
            });
            columns.AddChild(new LineEdit
            {
                PlaceHolder = pronoun.Value,
                MinSize = new Vector2(70, 0)
            });
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_entityManager.TryGetEntity(_target, out var uid) ||
            !_entityManager.TryGetComponent<GrammarComponent>(uid, out var grammar))
        {
            return;
        }

        if (_grammar.TryGetPronouns((uid.Value, grammar), out var pronouns) &&
            pronouns.Count != _pronouns.Count &&
            pronouns.Except(_pronouns).Any())
        {
            SetPronouns(pronouns);
        }
    }

    /// <summary>
    ///     When edits are saved, update cached pronouns and set pronouns for the target entity.
    /// </summary>
    private void SavePressed(BaseButton.ButtonEventArgs args)
    {
        Dictionary<PronounGrammarPrototype, string> newPronouns = [];

        if (!_entityManager.TryGetEntity(_target, out var uid) ||
            !_entityManager.TryGetComponent<GrammarComponent>(uid, out var grammar))
        {
            return;
        }

        foreach (var pair in PronounBox.Children)
        {
            if (pair.GetChild(0) is not Label inflection ||
                inflection.Text is null ||
                pair.GetChild(1) is not LineEdit pronoun)
            {
                continue;
            }

            if (!_protoMan.TryIndex<PronounGrammarPrototype>(inflection.Text, out var inflectionProto))
                continue;

            newPronouns.Add(inflectionProto, pronoun.Text);
        }

        foreach (var pronoun in newPronouns)
            _grammar.SetPronoun((uid.Value, grammar), pronoun);
    }

    private void ResetPressed(BaseButton.ButtonEventArgs args)
    {

    }
}
