using System.Linq;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects.Components.Localization;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.EditPronouns;

/// <summary>
///     Admin Eui window to view or edit an entity's pronouns.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EditPronounsWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    private readonly GrammarSystem _grammar = default!;

    private NetEntity _target = NetEntity.Invalid;
    private Dictionary<ProtoId<PronounGrammarPrototype>, string> _pronouns = [];

    private List<ProtoId<PronounGrammarPrototype>> _removedPronouns = [];
    private List<PronounGrammarPrototype> _inflections = [];

    public Action<(NetEntity target, Dictionary<ProtoId<PronounGrammarPrototype>, string> pronouns)>? OnSaveMessage;

    public EditPronounsWindow()
    {
        IoCManager.InjectDependencies(this);
        _grammar = _entityManager.System<GrammarSystem>();
        RobustXamlLoader.Load(this);

        AddButton.OnPressed += AddPressed;
        SaveButton.OnPressed += SavePressed;
        ResetButton.OnPressed += ResetPressed;
        NewDropdown.OnItemSelected += AddPronoun;
    }

    public void SetTargetEntity(NetEntity target)
    {
        _target = target;
        var uid = _entityManager.GetEntity(target);

        var targetName = _entityManager.EntityExists(uid)
                ? _entityManager.GetComponent<MetaDataComponent>(uid).EntityName
                : string.Empty;

        Title = Loc.GetString("edit-pronouns-title", ("targetName", targetName));
    }

    /// <summary>
    ///     Sets the list of pronouns.
    /// </summary>
    public void SetPronouns(Dictionary<ProtoId<PronounGrammarPrototype>, string> pronouns)
    {
        PronounContainer.DisposeAllChildren();
        _pronouns = pronouns;

        foreach (var pronoun in pronouns)
            AddPronounEntry(pronoun);
    }

    private void AddPronounEntry(KeyValuePair<ProtoId<PronounGrammarPrototype>, string> pronoun)
    {
        var entry = new PronounEntry(pronoun);
        entry.OnRemove += args =>
        {
            PronounContainer.RemoveChild(entry);
            _removedPronouns.Add(entry.Inflection);
        };
        entry.InflectionLabel.ToolTip = Loc.GetString(_protoMan.Index(pronoun.Key).Description);

        PronounContainer.AddChild(entry);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_entityManager.TryGetEntity(_target, out var uid) ||
            !_entityManager.TryGetComponent<GrammarComponent>(uid, out var grammar))
        {
            return;
        }

        if (_grammar.TryGetPronouns((uid.Value, grammar), out var pronouns) &&
            (pronouns.Count != _pronouns.Count ||
            pronouns.Except(_pronouns).Any()))
        {
            SetPronouns(pronouns);
        }
    }

    /// <summary>
    ///     Adds a new dropdown to the list from which a new inflection may be selected.
    /// </summary>
    private void AddPressed(BaseButton.ButtonEventArgs args)
    {
        _inflections.Clear();
        NewDropdown.Clear();

        // dropdown should only show inflections that we dont have!
        var protos = _protoMan.EnumeratePrototypes<PronounGrammarPrototype>().ToList();
        foreach (var child in PronounContainer.Children)
        {
            if (child is not PronounEntry entry)
                continue;
            protos.Remove(_protoMan.Index(entry.Inflection));
        }

        foreach (var inflection in protos)
        {
            NewDropdown.AddItem(Loc.GetString(inflection.Name));
            _inflections.Add(inflection);
        }
        NewDropdown.Visible = true;
        AddButton.Disabled = true;
    }

    /// <summary>
    ///     Adds the selected option in the dropdown as a new pronoun
    /// </summary>
    private void AddPronoun(OptionButton.ItemSelectedEventArgs args)
    {
        var inflection = _inflections[args.Id];
        var pronoun = new KeyValuePair<ProtoId<PronounGrammarPrototype>, string>(inflection.ID, "");

        AddPronounEntry(pronoun);

        NewDropdown.Visible = false;
        AddButton.Disabled = false;
        _removedPronouns.Remove(inflection.ID);
    }

    /// <summary>
    ///     When edits are saved, update cached pronouns and set pronouns for the target entity.
    /// </summary>
    private void SavePressed(BaseButton.ButtonEventArgs args)
    {
        Dictionary<ProtoId<PronounGrammarPrototype>, string> newPronouns = [];

        foreach (var child in _removedPronouns)
            newPronouns.Add(child, "");

        foreach (var child in PronounContainer.Children)
        {
            if (child is not PronounEntry entry ||
            entry.PronounLineEdit.Text is "")
                continue;
            newPronouns.Add(entry.Inflection, entry.PronounLineEdit.Text);
        }

        OnSaveMessage?.Invoke((_target, newPronouns));
        _removedPronouns.Clear();
    }

    /// <summary>
    ///     Resets any edited values.
    /// </summary>
    private void ResetPressed(BaseButton.ButtonEventArgs args)
    {
        SetPronouns(_pronouns);
        _removedPronouns.Clear();
    }
}
