using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.EditPronouns;

[GenerateTypedNameReferences]
public sealed partial class PronounEntry : Control
{
    [Dependency] private IPrototypeManager _protoMan = default!;
    public ProtoId<PronounGrammarPrototype> Inflection = default!;
    public event Action<PronounEntry>? OnRemove;

    public PronounEntry(KeyValuePair<ProtoId<PronounGrammarPrototype>, string> pronoun)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Inflection = pronoun.Key;
        InflectionLabel.Text = Loc.GetString(_protoMan.Index(Inflection).Name);
        PronounLineEdit.PlaceHolder = pronoun.Value;

        RemoveButton.OnPressed += _ => OnRemove?.Invoke(this);
    }
}
