using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class TriageBotMenu : FancyWindow
{
    public string CurrentMode = string.Empty;
    public event Action<string>? OnModeChanged;

    public TriageBotMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ModeOption.OnItemSelected += args =>
        {
            var metadata = ModeOption.GetItemMetadata(args.Id);
            if (metadata != null && metadata is string cast)
            {
                OnModeChanged?.Invoke(cast);
            }
        };
    }
}
