- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  #- Atlas
  - Bagel
  - Banana
  - Barratry
  - Bedlam
  - Boat
  - Box
  #- Cluster
  - Cog
  - Convex
  - Core
  - Elkridge
  #- Fland
  - Gate
  - Hummingbird
  - Hash
  - Lilboat
  - Luna
  #- Loop
  - Marathon
  #- Meta
  - Oasis
  - Omega
  - Packed
  - Plasma
  - Reach
  - Saltern
  - Submarine
  - Train
  - Union
  - Xeno
