- type: entity
  id: BaseStationServiceJobs
  abstract: true
  components:
  - type: ServiceJobsData

- type: entity
  id: BaseStationNanoChatLogs
  abstract: true
  components:
  - type: StationNanoChatLogs
