name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested]

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: Needs Review"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "S: Awaiting Changes"
